// Generated by Selenium IDE
import org.openqa.selenium.By;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.testng.annotations.AfterTest;
import org.testng.annotations.BeforeTest;
import org.testng.annotations.Test;

import java.util.HashMap;
import java.util.Map;
public class SARMRA {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @BeforeTest
  public void setUp() {
    driver = new FirefoxDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @AfterTest
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void SARMRA() {
    driver.get("http://10.10.108.20:7001/abfx/login.action");
    driver.manage().window().setSize(new Dimension(1920, 1080));
    driver.findElement(By.id("j_username")).sendKeys("cx_admin");
    driver.findElement(By.name("j_password")).sendKeys("111111");
    driver.findElement(By.name("j_captcha")).click();
    driver.findElement(By.name("j_captcha")).sendKeys("1111");
    driver.findElement(By.id("IbtnEnter")).click();
    driver.findElement(By.linkText("评估计划管理")).click();
    driver.findElement(By.id("ext-gen88")).click();
    driver.findElement(By.id("ext-comp-1054")).click();
    driver.findElement(By.id("ext-comp-1054")).click();
    driver.findElement(By.id("ext-comp-1054")).sendKeys("自动化测试脚本");
    driver.findElement(By.id("ext-comp-1055")).sendKeys("自动化");
    driver.findElement(By.id("ext-gen219")).click();
    driver.findElement(By.id("ext-gen241")).click();
    driver.findElement(By.id("ext-gen190")).click();
    driver.findElement(By.cssSelector("#ext-comp-1067 .x-btn-bc")).click();
    driver.findElement(By.linkText("退出系统")).click();
    driver.findElement(By.id("j_username")).sendKeys("cx_admin");
    driver.findElement(By.name("j_password")).sendKeys("111111");
  }
}
